# x — natural language to shell commands (zsh integration)
#
# Wraps the accept-line widget: when the buffer starts with the trigger
# word, the raw buffer (never parsed by zsh, so quotes/globs in natural
# language are safe) is sent to `x gen` and replaced with the generated
# command for review. Press Enter again to run it.
#
#   X_TRIGGER  trigger prefix (default: x).  e.g. export X_TRIGGER=@
#   X_TAG      comment appended to generated commands; set empty to disable.

(( ${+_X_ZSH_LOADED} )) && return
typeset -g _X_ZSH_LOADED=1

# needed so the trailing "# generated by x" tag is accepted when executed
setopt interactive_comments

typeset -g X_TRIGGER="${X_TRIGGER:-x}"
typeset -g X_TAG="${X_TAG-# generated by x}"

_x_accept_line() {
  if [[ $BUFFER == "$X_TRIGGER "* ]]; then
    local query=${BUFFER#"$X_TRIGGER" }
    # let the binary's real subcommands through untouched
    case ${query%% *} in
      gen|auth|init|help|-h|--help|-V|--version)
        zle .accept-line
        return
        ;;
    esac
    print -s -- "$BUFFER"  # keep the natural language query in history
    zle -M "x: generating…"
    local out
    out=$(command x gen --shell zsh -- "$query" 2>&1)
    if (( $? == 0 )) && [[ -n $out ]]; then
      BUFFER=$out
      [[ -n $X_TAG ]] && BUFFER="$BUFFER  $X_TAG"
      CURSOR=$#BUFFER
      zle -M ""
    else
      zle -M "x: ${out:-generation failed}"
    fi
    return 0
  fi
  zle .accept-line
}

zle -N accept-line _x_accept_line
