# x — natural language to shell commands (zsh integration)
#
# Press Tab on an empty line to enter "x mode": a marker (󰚩) appears at the
# start of the line and whatever you type is treated as natural language —
# never parsed by zsh, so quotes/globs/redirections in the query are safe and
# are shown in a single muted colour instead of being syntax-highlighted as
# shell operators. Press Enter to send the query to `x gen`; the line is then
# replaced by the generated command for review (Enter again runs it).
#
# Exit x mode without generating: Backspace on an empty line.
#
#   X_MODE_MARKER   text shown at the line start in x mode (default: "󰚩 ")
#   X_MARKER_STYLE  highlight for the marker          (default: fg=cyan,bold)
#   X_MODE_STYLE    highlight for the typed query     (default: fg=8, muted)
#   X_TAG           comment appended to generated commands (default: none).
#                   e.g. export X_TAG='# generated by x'

(( ${+_X_ZSH_LOADED} )) && return
typeset -g _X_ZSH_LOADED=1

# comments are accepted when executed (the model may answer non-command
# requests with a `# ...` line, and X_TAG is a comment too)
setopt interactive_comments
# sysread: lets _x_generate poll the stream with a timeout to animate a spinner
zmodload zsh/system

typeset -g X_MODE_MARKER="${X_MODE_MARKER-󰚩 }"
typeset -g X_MARKER_STYLE="${X_MARKER_STYLE:-fg=cyan,bold}"
typeset -g X_MODE_STYLE="${X_MODE_STYLE:-fg=8}"
typeset -g X_TAG="${X_TAG-}"
typeset -g X_SPIN_TEXT="${X_SPIN_TEXT- generating…}"

typeset -g _x_mode=          # non-empty while composing a query
typeset -g _x_tab_fallback=  # widget Tab was bound to before we took it over

_x_enter_mode() {
  # only hijack Tab on an empty line; otherwise fall back to completion
  if [[ -n $BUFFER || -n $_x_mode ]]; then
    zle "${_x_tab_fallback:-expand-or-complete}"
    return
  fi
  _x_mode=1
  PREDISPLAY=$X_MODE_MARKER
  zle -R
}

_x_exit_mode() {
  _x_mode=
  PREDISPLAY=
}

# Backspace on an empty query leaves x mode instead of beeping.
_x_backspace() {
  if [[ -n $_x_mode && -z $BUFFER ]]; then
    _x_exit_mode
    zle -R
    return
  fi
  zle backward-delete-char
}

# Runs on every redraw (registered after syntax-highlighting, so we win): in x
# mode, paint the marker accented and the whole query a single muted colour,
# overriding any operator highlighting. The `P` flag indexes into PREDISPLAY.
_x_highlight() {
  [[ -n $_x_mode ]] || return
  region_highlight=(
    "P0 ${#X_MODE_MARKER} $X_MARKER_STYLE"
    "0 ${#BUFFER} $X_MODE_STYLE"
  )
}

_x_accept_line() {
  if [[ -n $_x_mode ]]; then
    local query=$BUFFER
    _x_exit_mode
    if [[ -z $query ]]; then
      zle reset-prompt
      return 0
    fi
    print -s -- "$query"   # keep the natural-language query in history
    BUFFER=
    # echo the query above so it stays on screen (REPL-style); the generated
    # command then streams onto a fresh prompt line below it, instead of
    # replacing the query in place
    zle -I
    print -r -- "${X_MODE_MARKER}${query}"
    _x_generate "$query"
    return 0
  fi
  zle .accept-line
}

_x_generate() {
  local query=$1 got errf fd chunk acc had
  errf=$(mktemp)
  exec {fd}< <(command x gen --shell zsh --stream -- "$query" 2>$errf)
  # Poll with sysread so we can animate a spinner while waiting for the model:
  # rc 0 = bytes ready, rc 4 = timeout (spin a frame), rc 5 = EOF (done).
  # `x gen --stream` prints the command-so-far one line at a time; we split on
  # newlines and redraw the buffer so the command appears to type itself.
  local -a spin=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
  local si=1
  got= acc=
  zle -M "${spin[1]}${X_SPIN_TEXT}"
  while true; do
    sysread -t 0.08 -i $fd chunk
    case $? in
      0)
        acc+=$chunk
        had=
        while [[ $acc == *$'\n'* ]]; do
          got=${acc%%$'\n'*}; acc=${acc#*$'\n'}; had=1
        done
        if [[ -n $had ]]; then
          BUFFER=$got; CURSOR=$#BUFFER; zle -R
        fi
        ;;
      4)  # timeout: advance the spinner
        si=$(( si % ${#spin} + 1 ))
        zle -M "${spin[si]}${X_SPIN_TEXT}"
        ;;
      *)  break ;;   # 5 = EOF, anything else = error
    esac
  done
  [[ -z $got && -n $acc ]] && got=$acc   # trailing line without newline
  exec {fd}<&-
  # discard keys typed while generation blocked the editor: they would land
  # inside the command (or a queued Enter would run it without review)
  local _junk
  while (( PENDING > 0 )); do read -k 1 _junk; done
  if [[ -n $got ]]; then
    BUFFER=$got
    [[ -n $X_TAG ]] && BUFFER="$BUFFER  $X_TAG"
    CURSOR=$#BUFFER
    # full redraw: `zle -M ""` does not erase the "generating…" message
    zle reset-prompt
  else
    zle -M "x: ${$(<$errf):-generation failed}"
  fi
  rm -f $errf
}

zle -N _x_enter_mode
zle -N _x_backspace
zle -N accept-line _x_accept_line

# Install key bindings and the highlight hook from precmd, so this runs after
# every other plugin (notably zsh-syntax-highlighting) has set up its own
# line-pre-redraw hook and Tab binding — ours then take effect last. Runs once.
_x_install() {
  autoload -Uz add-zle-hook-widget add-zsh-hook

  # remember what Tab was bound to (fzf-tab, expand-or-complete, …) so we can
  # delegate to it on a non-empty line, then claim Tab for ourselves
  local cur
  for km in main viins emacs; do
    cur=${${(z)$(bindkey -M $km '^I' 2>/dev/null)}[2]}
    [[ -n $cur && $cur != _x_enter_mode ]] && _x_tab_fallback=$cur
    bindkey -M $km '^I' _x_enter_mode 2>/dev/null
    bindkey -M $km '^?' _x_backspace 2>/dev/null
  done

  add-zle-hook-widget line-pre-redraw _x_highlight
  add-zsh-hook -d precmd _x_install
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd _x_install
